// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {traversal} from '../models';

export function ChooseOption(arg1:string):Promise<void>;

export function GetCurrent():Promise<traversal.Option>;

export function GetOptions(arg1:string):Promise<Array<traversal.Option>>;

export function Initialize(arg1:string,arg2:string):Promise<void>;
