// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseOption(arg1) {
  return window['go']['main']['App']['ChooseOption'](arg1);
}

export function GetCurrent() {
  return window['go']['main']['App']['GetCurrent']();
}

export function GetOptions(arg1) {
  return window['go']['main']['App']['GetOptions'](arg1);
}

export function Initialize(arg1, arg2) {
  return window['go']['main']['App']['Initialize'](arg1, arg2);
}
